// Code generated by ts2go batch. DO NOT EDIT.

package grammars

import "github.com/odvcencio/gotreesitter"

func init() {
	Register(LangEntry{
		Name:       "comment",
		Extensions: nil,
		Language: func() *gotreesitter.Language {
			lang := CommentLanguage()
			lang.ExternalScanner = CommentExternalScanner{}
			return lang
		},
		HighlightQuery:     commentHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("comment"),
	})
}

const commentHighlightQuery = ""
