// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "tsx",
		Extensions:     []string{".tsx"},
		Language:       TsxLanguage,
		HighlightQuery: tsxHighlightQuery,
		TagsQuery:      tsxTagsQuery,
		TokenSourceFactory: defaultTokenSourceFactory("tsx"),
	})
}

const tsxTagsQuery = `(function_declaration
  (identifier) @name) @definition.function
(method_definition
  (property_identifier) @name) @definition.method
(class_declaration
  (type_identifier) @name) @definition.class
(interface_declaration
  (type_identifier) @name) @definition.interface
(variable_declarator
  (identifier) @name
  [(function_expression) (arrow_function)]) @definition.function
(call_expression
  (identifier) @name) @reference.call
(call_expression
  (member_expression
    (property_identifier) @name)) @reference.call
`

const tsxHighlightQuery = "; Types\n\n(type_identifier) @type\n(predefined_type) @type.builtin\n\n((identifier) @type\n (#match? @type \"^[A-Z]\"))\n\n(type_arguments\n  \"<\" @punctuation.bracket\n  \">\" @punctuation.bracket)\n\n; Variables\n\n(required_parameter (identifier) @variable.parameter)\n(optional_parameter (identifier) @variable.parameter)\n\n; Keywords\n\n[ \"abstract\"\n  \"declare\"\n  \"enum\"\n  \"export\"\n  \"implements\"\n  \"interface\"\n  \"keyof\"\n  \"namespace\"\n  \"private\"\n  \"protected\"\n  \"public\"\n  \"type\"\n  \"readonly\"\n  \"override\"\n  \"satisfies\"\n] @keyword\n"
