// Code generated by ts2go batch, then manually extended with TagsQuery.

package grammars

const watTagsQuery = `
(identifier) @name @definition.function
`

func init() {
	Register(LangEntry{
		Name:               "wat",
		Extensions:         []string{".wat", ".wast"},
		Language:            WatLanguage,
		HighlightQuery:     watHighlightQuery,
		TagsQuery:          watTagsQuery,
		TokenSourceFactory: defaultTokenSourceFactory("wat"),
	})
}

const watHighlightQuery = ""
