package grep

import (
	"fmt"
	"strings"

	"github.com/odvcencio/gotreesitter"
)

// Result represents a single structural match of a pattern against source code.
type Result struct {
	// StartByte is the byte offset where the overall match begins.
	StartByte uint32

	// EndByte is the byte offset where the overall match ends (exclusive).
	EndByte uint32

	// Captures maps user-facing metavariable names (e.g., "NAME", "PARAMS")
	// to the captured node information.
	Captures map[string]Capture
}

// Capture holds information about a single captured node within a match.
type Capture struct {
	// Name is the user-facing metavariable name (e.g., "NAME", "PARAMS").
	Name string

	// Text is the source text of the captured node.
	Text []byte

	// StartByte is the byte offset where the capture begins.
	StartByte uint32

	// EndByte is the byte offset where the capture ends (exclusive).
	EndByte uint32

	// Node is the captured syntax tree node.
	Node *gotreesitter.Node
}

// Match finds all structural matches of a code pattern in source code.
// The pattern may contain metavariables ($NAME, $$$NAME, $_, $NAME:type).
// Returns an empty slice (not an error) when no matches are found.
func Match(lang *gotreesitter.Language, pattern string, source []byte) ([]Result, error) {
	cp, err := CompilePattern(lang, pattern)
	if err != nil {
		return nil, fmt.Errorf("match: %w", err)
	}
	return executeMatch(cp, source)
}

// MatchSexp finds matches using a raw S-expression query string.
// This bypasses the code-pattern compiler and uses the S-expression directly
// as a tree-sitter query. Returns an empty slice when no matches are found.
func MatchSexp(lang *gotreesitter.Language, sexp string, source []byte) ([]Result, error) {
	if lang == nil {
		return nil, fmt.Errorf("matchsexp: nil language")
	}
	if strings.TrimSpace(sexp) == "" {
		return nil, fmt.Errorf("matchsexp: empty S-expression")
	}

	query, err := gotreesitter.NewQuery(sexp, lang)
	if err != nil {
		return nil, fmt.Errorf("matchsexp: query compile: %w", err)
	}

	cp := &CompiledPattern{
		Query:    query,
		MetaVars: nil,
		Lang:     lang,
		SExpr:    sexp,
	}
	return executeMatch(cp, source)
}

// Compile parses a code pattern into a reusable CompiledPattern.
// The returned pattern can be matched against multiple source files
// via its Match method without re-compilation.
func Compile(lang *gotreesitter.Language, pattern string) (*CompiledPattern, error) {
	return CompilePattern(lang, pattern)
}

// Match executes this compiled pattern against source code, returning all
// structural matches. Returns an empty slice when no matches are found.
func (cp *CompiledPattern) Match(source []byte) ([]Result, error) {
	return executeMatch(cp, source)
}

// executeMatch is the shared implementation for all match entry points.
// It parses the source, executes the compiled query, and converts the
// tree-sitter results into Result/Capture structs.
func executeMatch(cp *CompiledPattern, source []byte) ([]Result, error) {
	if cp == nil || cp.Query == nil || cp.Lang == nil {
		return nil, fmt.Errorf("execute: nil compiled pattern or query")
	}

	tree, err := parseSnippet(cp.Lang, source)
	if err != nil {
		return nil, fmt.Errorf("execute: parse source: %w", err)
	}
	bt := gotreesitter.Bind(tree)
	defer bt.Release()

	root := bt.RootNode()
	if root == nil {
		return []Result{}, nil
	}

	// Build reverse lookup: capture name in S-expression → user-facing
	// metavariable name. Internal captures (like _lit_N) are excluded.
	capToMeta := buildCaptureMap(cp.MetaVars)

	matches := cp.Query.ExecuteNode(root, cp.Lang, source)
	results := make([]Result, 0, len(matches))

	for _, m := range matches {
		r := convertMatch(m, source, capToMeta)
		results = append(results, r)
	}

	return results, nil
}

// buildCaptureMap builds a mapping from S-expression capture names to
// user-facing metavariable names. Captures generated by the compiler
// for metavariables use the metavariable's Name as the capture name
// (e.g., @NAME, @PARAMS), so the mapping is straightforward.
func buildCaptureMap(mvars map[string]*MetaVar) map[string]string {
	if len(mvars) == 0 {
		return nil
	}
	m := make(map[string]string, len(mvars))
	for _, mv := range mvars {
		if mv.Wildcard {
			continue // wildcards ($_ ) don't produce named captures
		}
		m[mv.Name] = mv.Name
	}
	return m
}

// convertMatch converts a single tree-sitter QueryMatch into a Result.
func convertMatch(qm gotreesitter.QueryMatch, source []byte, capToMeta map[string]string) Result {
	r := Result{
		StartByte: ^uint32(0), // max value, will be narrowed
		EndByte:   0,
		Captures:  make(map[string]Capture),
	}

	for _, qc := range qm.Captures {
		node := qc.Node
		if node == nil {
			continue
		}

		sb := node.StartByte()
		eb := node.EndByte()

		// Expand result span to cover all captures.
		if sb < r.StartByte {
			r.StartByte = sb
		}
		if eb > r.EndByte {
			r.EndByte = eb
		}

		// Determine the user-facing name. If the capture maps to a
		// metavariable, use that name. Otherwise, use the raw capture
		// name (for MatchSexp or literal captures).
		name := qc.Name
		if capToMeta != nil {
			if metaName, ok := capToMeta[name]; ok {
				name = metaName
			}
		}

		// Skip internal literal captures (e.g., _lit_1, _lit_2).
		if strings.HasPrefix(name, "_lit_") {
			continue
		}

		captureText := []byte(qc.Text(source))
		r.Captures[name] = Capture{
			Name:      name,
			Text:      captureText,
			StartByte: sb,
			EndByte:   eb,
			Node:      node,
		}
	}

	// If no captures contributed to the span, reset to zero.
	if r.StartByte == ^uint32(0) {
		r.StartByte = 0
		r.EndByte = 0
	}

	return r
}
